crawler: 
 url: https://www.zhihu.com/topic/19776749/hot
 pageProcessorThreadCount: 1
 downloadThreadCount: 1
 downloadSleep: 1500
 httpConfig:
  connectTimeout: 3000
  connectMaxTotal: 50
  encoding: UTF-8
  proxy: true
  headers:
   Accept: application/json,*/*;q=0.8
   Content-Type: application/json
   Accept-Encoding: gzip, deflate
   Accept-Language: zh-CN,zh;q=0.8
   User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
   Referer: https://www.zhihu.com/
   DNT: 1
  
 