crawler: 
 url: https://www.zhihu.com/topic/19776749/questions?page=
 page: 1
 limitTime: 1292795985000
 pageProcessorThreadCount: 3
 downloadThreadCount: 1
 downloadSleep: 1500
 httpConfig:
  connectTimeout: 3000
  connectMaxTotal: 50
  encoding: UTF-8
  proxy: ture
  headers:
   Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
   Content-Type: text/html; charset=UTF-8
   Accept-Encoding: gzip, deflate
   Accept-Language: zh-CN,zh;q=0.8
   User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
   Referer: https://www.zhihu.com/
   DNT: 1
  
 