crawler: 
 url: https://www.zhihu.com/topic/19776749/questions?page=1
 limit: 2014-1-27
 pageProcessorThreadCount: 3
 downloadThreadCount: 1
 httpConfig:
  connectTimeout: 3000
  connectMaxTotal: 50
  encoding: UTF-8
  proxy: true
  retryStatusCode: 500,503
  giveupStatusCode: 400,401,402,403,404,405,406,407,412,413,414,415,416,417,423,503,505
  headers:
   Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
   Content-Type: text/html; charset=UTF-8
   Accept-Encoding: gzip, deflate
   Accept-Language: zh-CN,zh;q=0.8
   User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
   Referer: https://www.zhihu.com/
   DNT: 1
  
 