crawler: 
 urls: http://www.ip3366.net/free/,http://ip.qiaodm.com/,http://www.kuaidaili.com/,http://www.sslproxies.org/,http://www.cool-proxy.net/proxies/http_proxy_list/sort:update_time/direction:desc/page:1,http://ip.izmoney.com/,http://free-proxy-list.net/,http://proxy.goubanjia.com/,http://www.socks-proxy.net/
 httpConfig:
  connectTimeout: 10000
  connectMaxTotal: 50
  encoding: UTF-8
  proxy: true
  retryStatusCode: 500,504
  giveUpStatusCode: 400,401.402,403,404,405,406,407,412,413,414,415,416,417,423,503,505
  headers:
   Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
   Accept-Language: zh-CN,zh;q=0.8
   User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
   Content-Type: text/html; charset=UTF-8
   Referer: https://www.baidu.com/