crawler: 
 urls: http://www.ip3366.net/free/,http://ip.qiaodm.com/,http://www.kuaidaili.com/,http://www.sslproxies.org/,http://free-proxy.cz/en/,http://www.cool-proxy.net/proxies/http_proxy_list/sort:update_time/direction:desc/page:1,http://www.cz88.net/proxy/,http://www.youdaili.net/,http://ip.izmoney.com/,http://free-proxy-list.net/,http://www.mrhinkydink.com/proxies.htm,http://proxy.goubanjia.com/,http://www.socks-proxy.net/,http://www.samair.ru/proxy/,http://www.xroxy.com/proxylist.htm,http://www.66ip.cn/,http://www.site-digger.com/html/articles/20110516/proxieslist.html,http://www.cn379.cn/
 httpConfig:
  connectTimeout: 3000
  connectMaxTotal: 50
  encoding: utf-8
  proxy: false
  retryStatusCode: 500,504
  giveUpStatusCode: 400,401.402,403,404,405,406,407,412,413,414,415,416,417,423,503,505	